[package]
name = "sacho"
description = "An opinionated changelog manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
caseless = "0.2.2"
clap = { version = "4.6.1", features = ["derive"] }
comrak = "0.53.0"
globset = "0.4.18"
hongdown = "0.5.1"
indexmap = { version = "2.12.1", features = ["serde"] }
jiff = "0.2.32"
miette = { version = "7.6.0", features = ["fancy"] }
semver = "1.0.28"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml_ng = "0.10.0"
similar = "3.1.1"
snafu = "0.9.1"
thiserror = "2.0.18"
toml = "1.1.2"
url = "2.5.8"

[dev-dependencies]
assert_cmd = "2.2.2"
mutants = "0.0.3"
predicates = "3.1.4"
portable-pty = "0.9.0"
proptest = "1.11.0"
tempfile = "3.27.0"

[target.'cfg(any(target_os = "android", target_os = "linux", target_vendor = "apple", target_os = "redox"))'.dependencies]
rustix = { version = "1.1.4", features = ["fs"] }

[target.'cfg(target_vendor = "apple")'.dependencies]
libc = "0.2.186"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Globalization", "Win32_Storage_FileSystem", "Win32_System_SystemServices"] }
